// Bundles the engine + three.js + GSAP into ONE offline HTML file, then:
//  - dist/roadmap-world.html            open in any browser (runs a sample journey)
//  - docs/index.html                    same file, served by GitHub Pages as the live demo
//  - react-native/roadmapWorldHtml.ts   the same HTML as a string for <WebView source={{ html }} />
import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';

const result = await build({
  entryPoints: ['src/webview-entry.js'],
  bundle: true,
  minify: true,
  format: 'iife',
  target: ['es2020', 'safari15', 'chrome90'],
  write: false,
  legalComments: 'none',
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<title>Roadmap World</title>
<style>
html,body{margin:0;height:100%;background:#9fd6f5;overflow:hidden;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,system-ui,sans-serif;overscroll-behavior:none}
#app{position:fixed;inset:0}
</style>
</head>
<body>
<div id="app"></div>
<script>${js}</script>
</body>
</html>
`;

mkdirSync('dist', { recursive: true });
mkdirSync('docs', { recursive: true });
writeFileSync('dist/roadmap-world.html', html);
writeFileSync('docs/index.html', html);
writeFileSync('docs/.nojekyll', '');
writeFileSync(
  'react-native/roadmapWorldHtml.ts',
  `// AUTO-GENERATED by scripts/build.mjs. Do not edit. Run \`npm run build\` after changing src/.\n` +
    `// eslint-disable-next-line\nexport const ROADMAP_WORLD_HTML: string = ${JSON.stringify(html)};\n`
);
console.log(`Built roadmap-world.html (${(html.length / 1024).toFixed(0)} KB)`);
